// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metric.proto

package io_containerd_cgroups_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Metrics struct {
	Hugetlb              []*HugetlbStat    `protobuf:"bytes,1,rep,name=hugetlb,proto3" json:"hugetlb,omitempty"`
	Pids                 *PidsStat         `protobuf:"bytes,2,opt,name=pids,proto3" json:"pids,omitempty"`
	CPU                  *CPUStat          `protobuf:"bytes,3,opt,name=CPU,proto3" json:"CPU,omitempty"`
	Memory               *MemoryStat       `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Blkio                *BlkIOStat        `protobuf:"bytes,5,opt,name=blkio,proto3" json:"blkio,omitempty"`
	Rdma                 *RdmaStat         `protobuf:"bytes,6,opt,name=rdma,proto3" json:"rdma,omitempty"`
	Network              []*NetworkStat    `protobuf:"bytes,7,rep,name=network,proto3" json:"network,omitempty"`
	CgroupStats          *CgroupStats      `protobuf:"bytes,8,opt,name=cgroup_stats,json=cgroupStats,proto3" json:"cgroup_stats,omitempty"`
	MemoryOomControl     *MemoryOomControl `protobuf:"bytes,9,opt,name=memory_oom_control,json=memoryOomControl,proto3" json:"memory_oom_control,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metrics) Reset()         { *m = Metrics{} }
func (m *Metrics) String() string { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()    {}
func (*Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{0}
}

func (m *Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metrics.Unmarshal(m, b)
}
func (m *Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metrics.Marshal(b, m, deterministic)
}
func (m *Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metrics.Merge(m, src)
}
func (m *Metrics) XXX_Size() int {
	return xxx_messageInfo_Metrics.Size(m)
}
func (m *Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Metrics proto.InternalMessageInfo

func (m *Metrics) GetHugetlb() []*HugetlbStat {
	if m != nil {
		return m.Hugetlb
	}
	return nil
}

func (m *Metrics) GetPids() *PidsStat {
	if m != nil {
		return m.Pids
	}
	return nil
}

func (m *Metrics) GetCPU() *CPUStat {
	if m != nil {
		return m.CPU
	}
	return nil
}

func (m *Metrics) GetMemory() *MemoryStat {
	if m != nil {
		return m.Memory
	}
	return nil
}

func (m *Metrics) GetBlkio() *BlkIOStat {
	if m != nil {
		return m.Blkio
	}
	return nil
}

func (m *Metrics) GetRdma() *RdmaStat {
	if m != nil {
		return m.Rdma
	}
	return nil
}

func (m *Metrics) GetNetwork() []*NetworkStat {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *Metrics) GetCgroupStats() *CgroupStats {
	if m != nil {
		return m.CgroupStats
	}
	return nil
}

func (m *Metrics) GetMemoryOomControl() *MemoryOomControl {
	if m != nil {
		return m.MemoryOomControl
	}
	return nil
}

type HugetlbStat struct {
	Usage                uint64   `protobuf:"varint,1,opt,name=usage,proto3" json:"usage,omitempty"`
	Max                  uint64   `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Failcnt              uint64   `protobuf:"varint,3,opt,name=failcnt,proto3" json:"failcnt,omitempty"`
	Pagesize             string   `protobuf:"bytes,4,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HugetlbStat) Reset()         { *m = HugetlbStat{} }
func (m *HugetlbStat) String() string { return proto.CompactTextString(m) }
func (*HugetlbStat) ProtoMessage()    {}
func (*HugetlbStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{1}
}

func (m *HugetlbStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HugetlbStat.Unmarshal(m, b)
}
func (m *HugetlbStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HugetlbStat.Marshal(b, m, deterministic)
}
func (m *HugetlbStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HugetlbStat.Merge(m, src)
}
func (m *HugetlbStat) XXX_Size() int {
	return xxx_messageInfo_HugetlbStat.Size(m)
}
func (m *HugetlbStat) XXX_DiscardUnknown() {
	xxx_messageInfo_HugetlbStat.DiscardUnknown(m)
}

var xxx_messageInfo_HugetlbStat proto.InternalMessageInfo

func (m *HugetlbStat) GetUsage() uint64 {
	if m != nil {
		return m.Usage
	}
	return 0
}

func (m *HugetlbStat) GetMax() uint64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *HugetlbStat) GetFailcnt() uint64 {
	if m != nil {
		return m.Failcnt
	}
	return 0
}

func (m *HugetlbStat) GetPagesize() string {
	if m != nil {
		return m.Pagesize
	}
	return ""
}

type PidsStat struct {
	Current              uint64   `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Limit                uint64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PidsStat) Reset()         { *m = PidsStat{} }
func (m *PidsStat) String() string { return proto.CompactTextString(m) }
func (*PidsStat) ProtoMessage()    {}
func (*PidsStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{2}
}

func (m *PidsStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PidsStat.Unmarshal(m, b)
}
func (m *PidsStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PidsStat.Marshal(b, m, deterministic)
}
func (m *PidsStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PidsStat.Merge(m, src)
}
func (m *PidsStat) XXX_Size() int {
	return xxx_messageInfo_PidsStat.Size(m)
}
func (m *PidsStat) XXX_DiscardUnknown() {
	xxx_messageInfo_PidsStat.DiscardUnknown(m)
}

var xxx_messageInfo_PidsStat proto.InternalMessageInfo

func (m *PidsStat) GetCurrent() uint64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *PidsStat) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type CPUStat struct {
	Usage                *CPUUsage `protobuf:"bytes,1,opt,name=usage,proto3" json:"usage,omitempty"`
	Throttling           *Throttle `protobuf:"bytes,2,opt,name=throttling,proto3" json:"throttling,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CPUStat) Reset()         { *m = CPUStat{} }
func (m *CPUStat) String() string { return proto.CompactTextString(m) }
func (*CPUStat) ProtoMessage()    {}
func (*CPUStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{3}
}

func (m *CPUStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPUStat.Unmarshal(m, b)
}
func (m *CPUStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPUStat.Marshal(b, m, deterministic)
}
func (m *CPUStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPUStat.Merge(m, src)
}
func (m *CPUStat) XXX_Size() int {
	return xxx_messageInfo_CPUStat.Size(m)
}
func (m *CPUStat) XXX_DiscardUnknown() {
	xxx_messageInfo_CPUStat.DiscardUnknown(m)
}

var xxx_messageInfo_CPUStat proto.InternalMessageInfo

func (m *CPUStat) GetUsage() *CPUUsage {
	if m != nil {
		return m.Usage
	}
	return nil
}

func (m *CPUStat) GetThrottling() *Throttle {
	if m != nil {
		return m.Throttling
	}
	return nil
}

type CPUUsage struct {
	// values in nanoseconds
	Total                uint64   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Kernel               uint64   `protobuf:"varint,2,opt,name=kernel,proto3" json:"kernel,omitempty"`
	User                 uint64   `protobuf:"varint,3,opt,name=user,proto3" json:"user,omitempty"`
	PerCPU               []uint64 `protobuf:"varint,4,rep,packed,name=PerCPU,proto3" json:"PerCPU,omitempty"`
	CfsPeriodUs          uint64   `protobuf:"varint,5,opt,name=cfs_period_us,json=cfsPeriodUs,proto3" json:"cfs_period_us,omitempty"`
	CfsQuotaUs           uint64   `protobuf:"varint,6,opt,name=cfs_quota_us,json=cfsQuotaUs,proto3" json:"cfs_quota_us,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPUUsage) Reset()         { *m = CPUUsage{} }
func (m *CPUUsage) String() string { return proto.CompactTextString(m) }
func (*CPUUsage) ProtoMessage()    {}
func (*CPUUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{4}
}

func (m *CPUUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPUUsage.Unmarshal(m, b)
}
func (m *CPUUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPUUsage.Marshal(b, m, deterministic)
}
func (m *CPUUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPUUsage.Merge(m, src)
}
func (m *CPUUsage) XXX_Size() int {
	return xxx_messageInfo_CPUUsage.Size(m)
}
func (m *CPUUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_CPUUsage.DiscardUnknown(m)
}

var xxx_messageInfo_CPUUsage proto.InternalMessageInfo

func (m *CPUUsage) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CPUUsage) GetKernel() uint64 {
	if m != nil {
		return m.Kernel
	}
	return 0
}

func (m *CPUUsage) GetUser() uint64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *CPUUsage) GetPerCPU() []uint64 {
	if m != nil {
		return m.PerCPU
	}
	return nil
}

func (m *CPUUsage) GetCfsPeriodUs() uint64 {
	if m != nil {
		return m.CfsPeriodUs
	}
	return 0
}

func (m *CPUUsage) GetCfsQuotaUs() uint64 {
	if m != nil {
		return m.CfsQuotaUs
	}
	return 0
}

type Throttle struct {
	Periods              uint64   `protobuf:"varint,1,opt,name=periods,proto3" json:"periods,omitempty"`
	ThrottledPeriods     uint64   `protobuf:"varint,2,opt,name=throttled_periods,json=throttledPeriods,proto3" json:"throttled_periods,omitempty"`
	ThrottledTime        uint64   `protobuf:"varint,3,opt,name=throttled_time,json=throttledTime,proto3" json:"throttled_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Throttle) Reset()         { *m = Throttle{} }
func (m *Throttle) String() string { return proto.CompactTextString(m) }
func (*Throttle) ProtoMessage()    {}
func (*Throttle) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{5}
}

func (m *Throttle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Throttle.Unmarshal(m, b)
}
func (m *Throttle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Throttle.Marshal(b, m, deterministic)
}
func (m *Throttle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Throttle.Merge(m, src)
}
func (m *Throttle) XXX_Size() int {
	return xxx_messageInfo_Throttle.Size(m)
}
func (m *Throttle) XXX_DiscardUnknown() {
	xxx_messageInfo_Throttle.DiscardUnknown(m)
}

var xxx_messageInfo_Throttle proto.InternalMessageInfo

func (m *Throttle) GetPeriods() uint64 {
	if m != nil {
		return m.Periods
	}
	return 0
}

func (m *Throttle) GetThrottledPeriods() uint64 {
	if m != nil {
		return m.ThrottledPeriods
	}
	return 0
}

func (m *Throttle) GetThrottledTime() uint64 {
	if m != nil {
		return m.ThrottledTime
	}
	return 0
}

type MemoryStat struct {
	Cache                   uint64       `protobuf:"varint,1,opt,name=cache,proto3" json:"cache,omitempty"`
	RSS                     uint64       `protobuf:"varint,2,opt,name=RSS,proto3" json:"RSS,omitempty"`
	RSSHuge                 uint64       `protobuf:"varint,3,opt,name=RSSHuge,proto3" json:"RSSHuge,omitempty"`
	MappedFile              uint64       `protobuf:"varint,4,opt,name=mapped_file,json=mappedFile,proto3" json:"mapped_file,omitempty"`
	Dirty                   uint64       `protobuf:"varint,5,opt,name=dirty,proto3" json:"dirty,omitempty"`
	Writeback               uint64       `protobuf:"varint,6,opt,name=writeback,proto3" json:"writeback,omitempty"`
	PgPgIn                  uint64       `protobuf:"varint,7,opt,name=pg_pg_in,json=pgPgIn,proto3" json:"pg_pg_in,omitempty"`
	PgPgOut                 uint64       `protobuf:"varint,8,opt,name=pg_pg_out,json=pgPgOut,proto3" json:"pg_pg_out,omitempty"`
	PgFault                 uint64       `protobuf:"varint,9,opt,name=pg_fault,json=pgFault,proto3" json:"pg_fault,omitempty"`
	PgMajFault              uint64       `protobuf:"varint,10,opt,name=pg_maj_fault,json=pgMajFault,proto3" json:"pg_maj_fault,omitempty"`
	InactiveAnon            uint64       `protobuf:"varint,11,opt,name=inactive_anon,json=inactiveAnon,proto3" json:"inactive_anon,omitempty"`
	ActiveAnon              uint64       `protobuf:"varint,12,opt,name=active_anon,json=activeAnon,proto3" json:"active_anon,omitempty"`
	InactiveFile            uint64       `protobuf:"varint,13,opt,name=inactive_file,json=inactiveFile,proto3" json:"inactive_file,omitempty"`
	ActiveFile              uint64       `protobuf:"varint,14,opt,name=active_file,json=activeFile,proto3" json:"active_file,omitempty"`
	Unevictable             uint64       `protobuf:"varint,15,opt,name=unevictable,proto3" json:"unevictable,omitempty"`
	HierarchicalMemoryLimit uint64       `protobuf:"varint,16,opt,name=hierarchical_memory_limit,json=hierarchicalMemoryLimit,proto3" json:"hierarchical_memory_limit,omitempty"`
	HierarchicalSwapLimit   uint64       `protobuf:"varint,17,opt,name=hierarchical_swap_limit,json=hierarchicalSwapLimit,proto3" json:"hierarchical_swap_limit,omitempty"`
	TotalCache              uint64       `protobuf:"varint,18,opt,name=total_cache,json=totalCache,proto3" json:"total_cache,omitempty"`
	TotalRSS                uint64       `protobuf:"varint,19,opt,name=TotalRSS,proto3" json:"TotalRSS,omitempty"`
	TotalRSSHuge            uint64       `protobuf:"varint,20,opt,name=TotalRSSHuge,proto3" json:"TotalRSSHuge,omitempty"`
	TotalMappedFile         uint64       `protobuf:"varint,21,opt,name=total_mapped_file,json=totalMappedFile,proto3" json:"total_mapped_file,omitempty"`
	TotalDirty              uint64       `protobuf:"varint,22,opt,name=total_dirty,json=totalDirty,proto3" json:"total_dirty,omitempty"`
	TotalWriteback          uint64       `protobuf:"varint,23,opt,name=total_writeback,json=totalWriteback,proto3" json:"total_writeback,omitempty"`
	TotalPgPgIn             uint64       `protobuf:"varint,24,opt,name=total_pg_pg_in,json=totalPgPgIn,proto3" json:"total_pg_pg_in,omitempty"`
	TotalPgPgOut            uint64       `protobuf:"varint,25,opt,name=total_pg_pg_out,json=totalPgPgOut,proto3" json:"total_pg_pg_out,omitempty"`
	TotalPgFault            uint64       `protobuf:"varint,26,opt,name=total_pg_fault,json=totalPgFault,proto3" json:"total_pg_fault,omitempty"`
	TotalPgMajFault         uint64       `protobuf:"varint,27,opt,name=total_pg_maj_fault,json=totalPgMajFault,proto3" json:"total_pg_maj_fault,omitempty"`
	TotalInactiveAnon       uint64       `protobuf:"varint,28,opt,name=total_inactive_anon,json=totalInactiveAnon,proto3" json:"total_inactive_anon,omitempty"`
	TotalActiveAnon         uint64       `protobuf:"varint,29,opt,name=total_active_anon,json=totalActiveAnon,proto3" json:"total_active_anon,omitempty"`
	TotalInactiveFile       uint64       `protobuf:"varint,30,opt,name=total_inactive_file,json=totalInactiveFile,proto3" json:"total_inactive_file,omitempty"`
	TotalActiveFile         uint64       `protobuf:"varint,31,opt,name=total_active_file,json=totalActiveFile,proto3" json:"total_active_file,omitempty"`
	TotalUnevictable        uint64       `protobuf:"varint,32,opt,name=total_unevictable,json=totalUnevictable,proto3" json:"total_unevictable,omitempty"`
	Usage                   *MemoryEntry `protobuf:"bytes,33,opt,name=usage,proto3" json:"usage,omitempty"`
	Swap                    *MemoryEntry `protobuf:"bytes,34,opt,name=swap,proto3" json:"swap,omitempty"`
	Kernel                  *MemoryEntry `protobuf:"bytes,35,opt,name=kernel,proto3" json:"kernel,omitempty"`
	KernelTCP               *MemoryEntry `protobuf:"bytes,36,opt,name=KernelTCP,proto3" json:"KernelTCP,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}     `json:"-"`
	XXX_unrecognized        []byte       `json:"-"`
	XXX_sizecache           int32        `json:"-"`
}

func (m *MemoryStat) Reset()         { *m = MemoryStat{} }
func (m *MemoryStat) String() string { return proto.CompactTextString(m) }
func (*MemoryStat) ProtoMessage()    {}
func (*MemoryStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{6}
}

func (m *MemoryStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryStat.Unmarshal(m, b)
}
func (m *MemoryStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryStat.Marshal(b, m, deterministic)
}
func (m *MemoryStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryStat.Merge(m, src)
}
func (m *MemoryStat) XXX_Size() int {
	return xxx_messageInfo_MemoryStat.Size(m)
}
func (m *MemoryStat) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryStat.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryStat proto.InternalMessageInfo

func (m *MemoryStat) GetCache() uint64 {
	if m != nil {
		return m.Cache
	}
	return 0
}

func (m *MemoryStat) GetRSS() uint64 {
	if m != nil {
		return m.RSS
	}
	return 0
}

func (m *MemoryStat) GetRSSHuge() uint64 {
	if m != nil {
		return m.RSSHuge
	}
	return 0
}

func (m *MemoryStat) GetMappedFile() uint64 {
	if m != nil {
		return m.MappedFile
	}
	return 0
}

func (m *MemoryStat) GetDirty() uint64 {
	if m != nil {
		return m.Dirty
	}
	return 0
}

func (m *MemoryStat) GetWriteback() uint64 {
	if m != nil {
		return m.Writeback
	}
	return 0
}

func (m *MemoryStat) GetPgPgIn() uint64 {
	if m != nil {
		return m.PgPgIn
	}
	return 0
}

func (m *MemoryStat) GetPgPgOut() uint64 {
	if m != nil {
		return m.PgPgOut
	}
	return 0
}

func (m *MemoryStat) GetPgFault() uint64 {
	if m != nil {
		return m.PgFault
	}
	return 0
}

func (m *MemoryStat) GetPgMajFault() uint64 {
	if m != nil {
		return m.PgMajFault
	}
	return 0
}

func (m *MemoryStat) GetInactiveAnon() uint64 {
	if m != nil {
		return m.InactiveAnon
	}
	return 0
}

func (m *MemoryStat) GetActiveAnon() uint64 {
	if m != nil {
		return m.ActiveAnon
	}
	return 0
}

func (m *MemoryStat) GetInactiveFile() uint64 {
	if m != nil {
		return m.InactiveFile
	}
	return 0
}

func (m *MemoryStat) GetActiveFile() uint64 {
	if m != nil {
		return m.ActiveFile
	}
	return 0
}

func (m *MemoryStat) GetUnevictable() uint64 {
	if m != nil {
		return m.Unevictable
	}
	return 0
}

func (m *MemoryStat) GetHierarchicalMemoryLimit() uint64 {
	if m != nil {
		return m.HierarchicalMemoryLimit
	}
	return 0
}

func (m *MemoryStat) GetHierarchicalSwapLimit() uint64 {
	if m != nil {
		return m.HierarchicalSwapLimit
	}
	return 0
}

func (m *MemoryStat) GetTotalCache() uint64 {
	if m != nil {
		return m.TotalCache
	}
	return 0
}

func (m *MemoryStat) GetTotalRSS() uint64 {
	if m != nil {
		return m.TotalRSS
	}
	return 0
}

func (m *MemoryStat) GetTotalRSSHuge() uint64 {
	if m != nil {
		return m.TotalRSSHuge
	}
	return 0
}

func (m *MemoryStat) GetTotalMappedFile() uint64 {
	if m != nil {
		return m.TotalMappedFile
	}
	return 0
}

func (m *MemoryStat) GetTotalDirty() uint64 {
	if m != nil {
		return m.TotalDirty
	}
	return 0
}

func (m *MemoryStat) GetTotalWriteback() uint64 {
	if m != nil {
		return m.TotalWriteback
	}
	return 0
}

func (m *MemoryStat) GetTotalPgPgIn() uint64 {
	if m != nil {
		return m.TotalPgPgIn
	}
	return 0
}

func (m *MemoryStat) GetTotalPgPgOut() uint64 {
	if m != nil {
		return m.TotalPgPgOut
	}
	return 0
}

func (m *MemoryStat) GetTotalPgFault() uint64 {
	if m != nil {
		return m.TotalPgFault
	}
	return 0
}

func (m *MemoryStat) GetTotalPgMajFault() uint64 {
	if m != nil {
		return m.TotalPgMajFault
	}
	return 0
}

func (m *MemoryStat) GetTotalInactiveAnon() uint64 {
	if m != nil {
		return m.TotalInactiveAnon
	}
	return 0
}

func (m *MemoryStat) GetTotalActiveAnon() uint64 {
	if m != nil {
		return m.TotalActiveAnon
	}
	return 0
}

func (m *MemoryStat) GetTotalInactiveFile() uint64 {
	if m != nil {
		return m.TotalInactiveFile
	}
	return 0
}

func (m *MemoryStat) GetTotalActiveFile() uint64 {
	if m != nil {
		return m.TotalActiveFile
	}
	return 0
}

func (m *MemoryStat) GetTotalUnevictable() uint64 {
	if m != nil {
		return m.TotalUnevictable
	}
	return 0
}

func (m *MemoryStat) GetUsage() *MemoryEntry {
	if m != nil {
		return m.Usage
	}
	return nil
}

func (m *MemoryStat) GetSwap() *MemoryEntry {
	if m != nil {
		return m.Swap
	}
	return nil
}

func (m *MemoryStat) GetKernel() *MemoryEntry {
	if m != nil {
		return m.Kernel
	}
	return nil
}

func (m *MemoryStat) GetKernelTCP() *MemoryEntry {
	if m != nil {
		return m.KernelTCP
	}
	return nil
}

type MemoryEntry struct {
	Limit                uint64   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Usage                uint64   `protobuf:"varint,2,opt,name=usage,proto3" json:"usage,omitempty"`
	Max                  uint64   `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Failcnt              uint64   `protobuf:"varint,4,opt,name=failcnt,proto3" json:"failcnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryEntry) Reset()         { *m = MemoryEntry{} }
func (m *MemoryEntry) String() string { return proto.CompactTextString(m) }
func (*MemoryEntry) ProtoMessage()    {}
func (*MemoryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{7}
}

func (m *MemoryEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryEntry.Unmarshal(m, b)
}
func (m *MemoryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryEntry.Marshal(b, m, deterministic)
}
func (m *MemoryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryEntry.Merge(m, src)
}
func (m *MemoryEntry) XXX_Size() int {
	return xxx_messageInfo_MemoryEntry.Size(m)
}
func (m *MemoryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryEntry proto.InternalMessageInfo

func (m *MemoryEntry) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *MemoryEntry) GetUsage() uint64 {
	if m != nil {
		return m.Usage
	}
	return 0
}

func (m *MemoryEntry) GetMax() uint64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *MemoryEntry) GetFailcnt() uint64 {
	if m != nil {
		return m.Failcnt
	}
	return 0
}

type MemoryOomControl struct {
	OomKillDisable       uint64   `protobuf:"varint,1,opt,name=oom_kill_disable,json=oomKillDisable,proto3" json:"oom_kill_disable,omitempty"`
	UnderOom             uint64   `protobuf:"varint,2,opt,name=under_oom,json=underOom,proto3" json:"under_oom,omitempty"`
	OomKill              uint64   `protobuf:"varint,3,opt,name=oom_kill,json=oomKill,proto3" json:"oom_kill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryOomControl) Reset()         { *m = MemoryOomControl{} }
func (m *MemoryOomControl) String() string { return proto.CompactTextString(m) }
func (*MemoryOomControl) ProtoMessage()    {}
func (*MemoryOomControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{8}
}

func (m *MemoryOomControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryOomControl.Unmarshal(m, b)
}
func (m *MemoryOomControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryOomControl.Marshal(b, m, deterministic)
}
func (m *MemoryOomControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryOomControl.Merge(m, src)
}
func (m *MemoryOomControl) XXX_Size() int {
	return xxx_messageInfo_MemoryOomControl.Size(m)
}
func (m *MemoryOomControl) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryOomControl.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryOomControl proto.InternalMessageInfo

func (m *MemoryOomControl) GetOomKillDisable() uint64 {
	if m != nil {
		return m.OomKillDisable
	}
	return 0
}

func (m *MemoryOomControl) GetUnderOom() uint64 {
	if m != nil {
		return m.UnderOom
	}
	return 0
}

func (m *MemoryOomControl) GetOomKill() uint64 {
	if m != nil {
		return m.OomKill
	}
	return 0
}

type BlkIOStat struct {
	IoServiceBytesRecursive []*BlkIOEntry `protobuf:"bytes,1,rep,name=io_service_bytes_recursive,json=ioServiceBytesRecursive,proto3" json:"io_service_bytes_recursive,omitempty"`
	IoServicedRecursive     []*BlkIOEntry `protobuf:"bytes,2,rep,name=io_serviced_recursive,json=ioServicedRecursive,proto3" json:"io_serviced_recursive,omitempty"`
	IoQueuedRecursive       []*BlkIOEntry `protobuf:"bytes,3,rep,name=io_queued_recursive,json=ioQueuedRecursive,proto3" json:"io_queued_recursive,omitempty"`
	IoServiceTimeRecursive  []*BlkIOEntry `protobuf:"bytes,4,rep,name=io_service_time_recursive,json=ioServiceTimeRecursive,proto3" json:"io_service_time_recursive,omitempty"`
	IoWaitTimeRecursive     []*BlkIOEntry `protobuf:"bytes,5,rep,name=io_wait_time_recursive,json=ioWaitTimeRecursive,proto3" json:"io_wait_time_recursive,omitempty"`
	IoMergedRecursive       []*BlkIOEntry `protobuf:"bytes,6,rep,name=io_merged_recursive,json=ioMergedRecursive,proto3" json:"io_merged_recursive,omitempty"`
	IoTimeRecursive         []*BlkIOEntry `protobuf:"bytes,7,rep,name=io_time_recursive,json=ioTimeRecursive,proto3" json:"io_time_recursive,omitempty"`
	SectorsRecursive        []*BlkIOEntry `protobuf:"bytes,8,rep,name=sectors_recursive,json=sectorsRecursive,proto3" json:"sectors_recursive,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}      `json:"-"`
	XXX_unrecognized        []byte        `json:"-"`
	XXX_sizecache           int32         `json:"-"`
}

func (m *BlkIOStat) Reset()         { *m = BlkIOStat{} }
func (m *BlkIOStat) String() string { return proto.CompactTextString(m) }
func (*BlkIOStat) ProtoMessage()    {}
func (*BlkIOStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{9}
}

func (m *BlkIOStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlkIOStat.Unmarshal(m, b)
}
func (m *BlkIOStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlkIOStat.Marshal(b, m, deterministic)
}
func (m *BlkIOStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlkIOStat.Merge(m, src)
}
func (m *BlkIOStat) XXX_Size() int {
	return xxx_messageInfo_BlkIOStat.Size(m)
}
func (m *BlkIOStat) XXX_DiscardUnknown() {
	xxx_messageInfo_BlkIOStat.DiscardUnknown(m)
}

var xxx_messageInfo_BlkIOStat proto.InternalMessageInfo

func (m *BlkIOStat) GetIoServiceBytesRecursive() []*BlkIOEntry {
	if m != nil {
		return m.IoServiceBytesRecursive
	}
	return nil
}

func (m *BlkIOStat) GetIoServicedRecursive() []*BlkIOEntry {
	if m != nil {
		return m.IoServicedRecursive
	}
	return nil
}

func (m *BlkIOStat) GetIoQueuedRecursive() []*BlkIOEntry {
	if m != nil {
		return m.IoQueuedRecursive
	}
	return nil
}

func (m *BlkIOStat) GetIoServiceTimeRecursive() []*BlkIOEntry {
	if m != nil {
		return m.IoServiceTimeRecursive
	}
	return nil
}

func (m *BlkIOStat) GetIoWaitTimeRecursive() []*BlkIOEntry {
	if m != nil {
		return m.IoWaitTimeRecursive
	}
	return nil
}

func (m *BlkIOStat) GetIoMergedRecursive() []*BlkIOEntry {
	if m != nil {
		return m.IoMergedRecursive
	}
	return nil
}

func (m *BlkIOStat) GetIoTimeRecursive() []*BlkIOEntry {
	if m != nil {
		return m.IoTimeRecursive
	}
	return nil
}

func (m *BlkIOStat) GetSectorsRecursive() []*BlkIOEntry {
	if m != nil {
		return m.SectorsRecursive
	}
	return nil
}

type BlkIOEntry struct {
	Op                   string   `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Device               string   `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Major                uint64   `protobuf:"varint,3,opt,name=major,proto3" json:"major,omitempty"`
	Minor                uint64   `protobuf:"varint,4,opt,name=minor,proto3" json:"minor,omitempty"`
	Value                uint64   `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlkIOEntry) Reset()         { *m = BlkIOEntry{} }
func (m *BlkIOEntry) String() string { return proto.CompactTextString(m) }
func (*BlkIOEntry) ProtoMessage()    {}
func (*BlkIOEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{10}
}

func (m *BlkIOEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlkIOEntry.Unmarshal(m, b)
}
func (m *BlkIOEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlkIOEntry.Marshal(b, m, deterministic)
}
func (m *BlkIOEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlkIOEntry.Merge(m, src)
}
func (m *BlkIOEntry) XXX_Size() int {
	return xxx_messageInfo_BlkIOEntry.Size(m)
}
func (m *BlkIOEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_BlkIOEntry.DiscardUnknown(m)
}

var xxx_messageInfo_BlkIOEntry proto.InternalMessageInfo

func (m *BlkIOEntry) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *BlkIOEntry) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *BlkIOEntry) GetMajor() uint64 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *BlkIOEntry) GetMinor() uint64 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *BlkIOEntry) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type RdmaStat struct {
	Current              []*RdmaEntry `protobuf:"bytes,1,rep,name=current,proto3" json:"current,omitempty"`
	Limit                []*RdmaEntry `protobuf:"bytes,2,rep,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RdmaStat) Reset()         { *m = RdmaStat{} }
func (m *RdmaStat) String() string { return proto.CompactTextString(m) }
func (*RdmaStat) ProtoMessage()    {}
func (*RdmaStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{11}
}

func (m *RdmaStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RdmaStat.Unmarshal(m, b)
}
func (m *RdmaStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RdmaStat.Marshal(b, m, deterministic)
}
func (m *RdmaStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RdmaStat.Merge(m, src)
}
func (m *RdmaStat) XXX_Size() int {
	return xxx_messageInfo_RdmaStat.Size(m)
}
func (m *RdmaStat) XXX_DiscardUnknown() {
	xxx_messageInfo_RdmaStat.DiscardUnknown(m)
}

var xxx_messageInfo_RdmaStat proto.InternalMessageInfo

func (m *RdmaStat) GetCurrent() []*RdmaEntry {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *RdmaStat) GetLimit() []*RdmaEntry {
	if m != nil {
		return m.Limit
	}
	return nil
}

type RdmaEntry struct {
	Device               string   `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	HcaHandles           uint32   `protobuf:"varint,2,opt,name=hca_handles,json=hcaHandles,proto3" json:"hca_handles,omitempty"`
	HcaObjects           uint32   `protobuf:"varint,3,opt,name=hca_objects,json=hcaObjects,proto3" json:"hca_objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RdmaEntry) Reset()         { *m = RdmaEntry{} }
func (m *RdmaEntry) String() string { return proto.CompactTextString(m) }
func (*RdmaEntry) ProtoMessage()    {}
func (*RdmaEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{12}
}

func (m *RdmaEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RdmaEntry.Unmarshal(m, b)
}
func (m *RdmaEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RdmaEntry.Marshal(b, m, deterministic)
}
func (m *RdmaEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RdmaEntry.Merge(m, src)
}
func (m *RdmaEntry) XXX_Size() int {
	return xxx_messageInfo_RdmaEntry.Size(m)
}
func (m *RdmaEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_RdmaEntry.DiscardUnknown(m)
}

var xxx_messageInfo_RdmaEntry proto.InternalMessageInfo

func (m *RdmaEntry) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *RdmaEntry) GetHcaHandles() uint32 {
	if m != nil {
		return m.HcaHandles
	}
	return 0
}

func (m *RdmaEntry) GetHcaObjects() uint32 {
	if m != nil {
		return m.HcaObjects
	}
	return 0
}

type NetworkStat struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RxBytes              uint64   `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	RxPackets            uint64   `protobuf:"varint,3,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`
	RxErrors             uint64   `protobuf:"varint,4,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
	RxDropped            uint64   `protobuf:"varint,5,opt,name=rx_dropped,json=rxDropped,proto3" json:"rx_dropped,omitempty"`
	TxBytes              uint64   `protobuf:"varint,6,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	TxPackets            uint64   `protobuf:"varint,7,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"`
	TxErrors             uint64   `protobuf:"varint,8,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`
	TxDropped            uint64   `protobuf:"varint,9,opt,name=tx_dropped,json=txDropped,proto3" json:"tx_dropped,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkStat) Reset()         { *m = NetworkStat{} }
func (m *NetworkStat) String() string { return proto.CompactTextString(m) }
func (*NetworkStat) ProtoMessage()    {}
func (*NetworkStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{13}
}

func (m *NetworkStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkStat.Unmarshal(m, b)
}
func (m *NetworkStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkStat.Marshal(b, m, deterministic)
}
func (m *NetworkStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkStat.Merge(m, src)
}
func (m *NetworkStat) XXX_Size() int {
	return xxx_messageInfo_NetworkStat.Size(m)
}
func (m *NetworkStat) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkStat.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkStat proto.InternalMessageInfo

func (m *NetworkStat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkStat) GetRxBytes() uint64 {
	if m != nil {
		return m.RxBytes
	}
	return 0
}

func (m *NetworkStat) GetRxPackets() uint64 {
	if m != nil {
		return m.RxPackets
	}
	return 0
}

func (m *NetworkStat) GetRxErrors() uint64 {
	if m != nil {
		return m.RxErrors
	}
	return 0
}

func (m *NetworkStat) GetRxDropped() uint64 {
	if m != nil {
		return m.RxDropped
	}
	return 0
}

func (m *NetworkStat) GetTxBytes() uint64 {
	if m != nil {
		return m.TxBytes
	}
	return 0
}

func (m *NetworkStat) GetTxPackets() uint64 {
	if m != nil {
		return m.TxPackets
	}
	return 0
}

func (m *NetworkStat) GetTxErrors() uint64 {
	if m != nil {
		return m.TxErrors
	}
	return 0
}

func (m *NetworkStat) GetTxDropped() uint64 {
	if m != nil {
		return m.TxDropped
	}
	return 0
}

// CgroupStats exports per-cgroup statistics.
type CgroupStats struct {
	// number of tasks sleeping
	NrSleeping uint64 `protobuf:"varint,1,opt,name=nr_sleeping,json=nrSleeping,proto3" json:"nr_sleeping,omitempty"`
	// number of tasks running
	NrRunning uint64 `protobuf:"varint,2,opt,name=nr_running,json=nrRunning,proto3" json:"nr_running,omitempty"`
	// number of tasks in stopped state
	NrStopped uint64 `protobuf:"varint,3,opt,name=nr_stopped,json=nrStopped,proto3" json:"nr_stopped,omitempty"`
	// number of tasks in uninterruptible state
	NrUninterruptible uint64 `protobuf:"varint,4,opt,name=nr_uninterruptible,json=nrUninterruptible,proto3" json:"nr_uninterruptible,omitempty"`
	// number of tasks waiting on IO
	NrIoWait             uint64   `protobuf:"varint,5,opt,name=nr_io_wait,json=nrIoWait,proto3" json:"nr_io_wait,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CgroupStats) Reset()         { *m = CgroupStats{} }
func (m *CgroupStats) String() string { return proto.CompactTextString(m) }
func (*CgroupStats) ProtoMessage()    {}
func (*CgroupStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_da41641f55bff5df, []int{14}
}

func (m *CgroupStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CgroupStats.Unmarshal(m, b)
}
func (m *CgroupStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CgroupStats.Marshal(b, m, deterministic)
}
func (m *CgroupStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CgroupStats.Merge(m, src)
}
func (m *CgroupStats) XXX_Size() int {
	return xxx_messageInfo_CgroupStats.Size(m)
}
func (m *CgroupStats) XXX_DiscardUnknown() {
	xxx_messageInfo_CgroupStats.DiscardUnknown(m)
}

var xxx_messageInfo_CgroupStats proto.InternalMessageInfo

func (m *CgroupStats) GetNrSleeping() uint64 {
	if m != nil {
		return m.NrSleeping
	}
	return 0
}

func (m *CgroupStats) GetNrRunning() uint64 {
	if m != nil {
		return m.NrRunning
	}
	return 0
}

func (m *CgroupStats) GetNrStopped() uint64 {
	if m != nil {
		return m.NrStopped
	}
	return 0
}

func (m *CgroupStats) GetNrUninterruptible() uint64 {
	if m != nil {
		return m.NrUninterruptible
	}
	return 0
}

func (m *CgroupStats) GetNrIoWait() uint64 {
	if m != nil {
		return m.NrIoWait
	}
	return 0
}

func init() {
	proto.RegisterType((*Metrics)(nil), "io.containerd.cgroups.v1.Metrics")
	proto.RegisterType((*HugetlbStat)(nil), "io.containerd.cgroups.v1.HugetlbStat")
	proto.RegisterType((*PidsStat)(nil), "io.containerd.cgroups.v1.PidsStat")
	proto.RegisterType((*CPUStat)(nil), "io.containerd.cgroups.v1.CPUStat")
	proto.RegisterType((*CPUUsage)(nil), "io.containerd.cgroups.v1.CPUUsage")
	proto.RegisterType((*Throttle)(nil), "io.containerd.cgroups.v1.Throttle")
	proto.RegisterType((*MemoryStat)(nil), "io.containerd.cgroups.v1.MemoryStat")
	proto.RegisterType((*MemoryEntry)(nil), "io.containerd.cgroups.v1.MemoryEntry")
	proto.RegisterType((*MemoryOomControl)(nil), "io.containerd.cgroups.v1.MemoryOomControl")
	proto.RegisterType((*BlkIOStat)(nil), "io.containerd.cgroups.v1.BlkIOStat")
	proto.RegisterType((*BlkIOEntry)(nil), "io.containerd.cgroups.v1.BlkIOEntry")
	proto.RegisterType((*RdmaStat)(nil), "io.containerd.cgroups.v1.RdmaStat")
	proto.RegisterType((*RdmaEntry)(nil), "io.containerd.cgroups.v1.RdmaEntry")
	proto.RegisterType((*NetworkStat)(nil), "io.containerd.cgroups.v1.NetworkStat")
	proto.RegisterType((*CgroupStats)(nil), "io.containerd.cgroups.v1.CgroupStats")
}

func init() { proto.RegisterFile("metric.proto", fileDescriptor_da41641f55bff5df) }

var fileDescriptor_da41641f55bff5df = []byte{
	// 1637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xd1, 0x6e, 0xdc, 0xc6,
	0x15, 0xc5, 0x6a, 0x57, 0xda, 0xdd, 0xbb, 0x92, 0x2c, 0x8d, 0x63, 0x9b, 0x56, 0x9c, 0x5a, 0xa1,
	0x6d, 0xd4, 0x88, 0x51, 0x01, 0x4d, 0x80, 0xa0, 0x4e, 0x1b, 0x14, 0xb1, 0x9c, 0xc0, 0x46, 0xaa,
	0x6a, 0xcd, 0x95, 0x90, 0xf4, 0x89, 0x18, 0x71, 0x47, 0xab, 0xb1, 0x48, 0x0e, 0x33, 0x1c, 0x4a,
	0xeb, 0x3e, 0x17, 0xe8, 0x53, 0xd1, 0xff, 0xe8, 0x1f, 0xf4, 0x23, 0xfa, 0xd8, 0xff, 0x29, 0xe6,
	0xde, 0x21, 0x39, 0x2b, 0x5b, 0x56, 0xf7, 0x6d, 0xef, 0x9d, 0x73, 0xce, 0xcc, 0x5c, 0x9e, 0x19,
	0x5e, 0x2e, 0xac, 0x67, 0xc2, 0x68, 0x99, 0xec, 0x15, 0x5a, 0x19, 0xc5, 0x02, 0xa9, 0xf6, 0x12,
	0x95, 0x1b, 0x2e, 0x73, 0xa1, 0xa7, 0x7b, 0xc9, 0x4c, 0xab, 0xaa, 0x28, 0xf7, 0x2e, 0x7e, 0x1b,
	0xfe, 0xa7, 0x07, 0xfd, 0x03, 0x84, 0x96, 0xec, 0x8f, 0xd0, 0x3f, 0xab, 0x66, 0xc2, 0xa4, 0x27,
	0x41, 0x67, 0xb7, 0xfb, 0x74, 0xf4, 0xe5, 0x93, 0xbd, 0xeb, 0x78, 0x7b, 0xaf, 0x08, 0x38, 0x31,
	0xdc, 0x44, 0x35, 0x8b, 0x7d, 0x0d, 0xbd, 0x42, 0x4e, 0xcb, 0x60, 0x65, 0xb7, 0xf3, 0x74, 0xf4,
	0x65, 0x78, 0x3d, 0x7b, 0x2c, 0xa7, 0x25, 0x52, 0x11, 0xcf, 0xbe, 0x82, 0xee, 0xfe, 0xf8, 0x38,
	0xe8, 0x22, 0xed, 0xf3, 0xeb, 0x69, 0xfb, 0xe3, 0x63, 0x64, 0x59, 0x34, 0xfb, 0x03, 0xac, 0x65,
	0x22, 0x53, 0xfa, 0x5d, 0xd0, 0x43, 0xde, 0xe3, 0xeb, 0x79, 0x07, 0x88, 0x43, 0xaa, 0xe3, 0xb0,
	0xe7, 0xb0, 0x7a, 0x92, 0x9e, 0x4b, 0x15, 0xac, 0x22, 0xf9, 0xd1, 0xf5, 0xe4, 0x17, 0xe9, 0xf9,
	0xeb, 0x43, 0xe4, 0x12, 0xc3, 0xee, 0x52, 0x4f, 0x33, 0x1e, 0xac, 0xdd, 0xb4, 0xcb, 0x68, 0x9a,
	0x71, 0xda, 0xa5, 0xc5, 0xdb, 0xf2, 0xe6, 0xc2, 0x5c, 0x2a, 0x7d, 0x1e, 0xf4, 0x6f, 0x2a, 0xef,
	0x9f, 0x09, 0x48, 0xe5, 0x75, 0x2c, 0xf6, 0x0a, 0xd6, 0x09, 0x12, 0x97, 0x86, 0x9b, 0x32, 0x18,
	0xe0, 0x02, 0x3e, 0xa2, 0xb2, 0x8f, 0x3f, 0xad, 0x48, 0x19, 0x8d, 0x92, 0x36, 0x60, 0x3f, 0x03,
	0xa3, 0x3a, 0xc4, 0x4a, 0x65, 0xb1, 0x25, 0x6b, 0x95, 0x06, 0x43, 0xd4, 0xfb, 0xe2, 0xa6, 0x3a,
	0x1e, 0xaa, 0x6c, 0x9f, 0x18, 0xd1, 0x56, 0x76, 0x25, 0x13, 0x9e, 0xc3, 0xc8, 0xb3, 0x06, 0xfb,
	0x04, 0x56, 0xab, 0x92, 0xcf, 0x44, 0xd0, 0xd9, 0xed, 0x3c, 0xed, 0x45, 0x14, 0xb0, 0x2d, 0xe8,
	0x66, 0x7c, 0x8e, 0x36, 0xe9, 0x45, 0xf6, 0x27, 0x0b, 0xa0, 0x7f, 0xca, 0x65, 0x9a, 0xe4, 0x06,
	0x5d, 0xd0, 0x8b, 0xea, 0x90, 0xed, 0xc0, 0xa0, 0xe0, 0x33, 0x51, 0xca, 0xbf, 0x0a, 0x7c, 0xd0,
	0xc3, 0xa8, 0x89, 0xc3, 0x6f, 0x60, 0x50, 0x3b, 0xc9, 0x2a, 0x24, 0x95, 0xd6, 0x22, 0x37, 0x6e,
	0xae, 0x3a, 0xb4, 0x6b, 0x48, 0x65, 0x26, 0x8d, 0x9b, 0x8f, 0x82, 0xf0, 0xef, 0x1d, 0xe8, 0x3b,
	0x3f, 0xb1, 0xdf, 0xf9, 0xab, 0xfc, 0xe8, 0x23, 0xdd, 0x1f, 0x1f, 0x1f, 0x5b, 0x64, 0xbd, 0x93,
	0x17, 0x00, 0xe6, 0x4c, 0x2b, 0x63, 0x52, 0x99, 0xcf, 0x6e, 0xf6, 0xfd, 0x11, 0x61, 0x45, 0xe4,
	0xb1, 0xc2, 0x7f, 0x75, 0x60, 0x50, 0xeb, 0xda, 0xc5, 0x1a, 0x65, 0x78, 0x5a, 0x17, 0x0c, 0x03,
	0x76, 0x17, 0xd6, 0xce, 0x85, 0xce, 0x45, 0xea, 0xf6, 0xe0, 0x22, 0xc6, 0xa0, 0x57, 0x95, 0x42,
	0xbb, 0x9a, 0xe1, 0x6f, 0x8b, 0x1d, 0x0b, 0x6d, 0xcf, 0x53, 0x6f, 0xb7, 0x6b, 0xb1, 0x14, 0xb1,
	0x10, 0x36, 0x92, 0xd3, 0x32, 0x2e, 0x84, 0x96, 0x6a, 0x1a, 0x57, 0x25, 0x3a, 0xbf, 0x17, 0x8d,
	0x92, 0xd3, 0x72, 0x8c, 0xb9, 0xe3, 0x92, 0xed, 0xc2, 0xba, 0xc5, 0xfc, 0x52, 0x29, 0xc3, 0x2d,
	0x64, 0x0d, 0x21, 0x90, 0x9c, 0x96, 0x6f, 0x6c, 0xea, 0xb8, 0x0c, 0xe7, 0x30, 0xa8, 0x37, 0x61,
	0x4b, 0x4e, 0x6a, 0x65, 0x5d, 0x72, 0x17, 0xb2, 0x67, 0xb0, 0xed, 0x36, 0x28, 0xa6, 0x71, 0x8d,
	0xa1, 0xa5, 0x6f, 0x35, 0x03, 0x63, 0x07, 0x7e, 0x02, 0x9b, 0x2d, 0xd8, 0xc8, 0x4c, 0xb8, 0xed,
	0x6c, 0x34, 0xd9, 0x23, 0x99, 0x89, 0xf0, 0x9f, 0x23, 0x80, 0xf6, 0x20, 0xdb, 0x42, 0x25, 0x3c,
	0x39, 0x6b, 0x9c, 0x85, 0x81, 0x75, 0x56, 0x34, 0x99, 0xd4, 0xce, 0x8a, 0x26, 0x13, 0xbb, 0xc8,
	0x68, 0x32, 0xb1, 0x9e, 0xac, 0x9d, 0xe5, 0x42, 0xf6, 0x10, 0x46, 0x19, 0x2f, 0x0a, 0x31, 0x8d,
	0x4f, 0x65, 0x4a, 0xe6, 0xea, 0x45, 0x40, 0xa9, 0x1f, 0x64, 0x8a, 0xcf, 0x62, 0x2a, 0xb5, 0x79,
	0xe7, 0x2a, 0x45, 0x01, 0x7b, 0x00, 0xc3, 0x4b, 0x2d, 0x8d, 0x38, 0xe1, 0xc9, 0xb9, 0x2b, 0x50,
	0x9b, 0x60, 0x01, 0x0c, 0x8a, 0x59, 0x5c, 0xcc, 0x62, 0x99, 0x07, 0x7d, 0x7a, 0x56, 0xc5, 0x6c,
	0x3c, 0x7b, 0x9d, 0xb3, 0x1d, 0x18, 0xd2, 0x88, 0xaa, 0x0c, 0x1e, 0x5d, 0x5b, 0xaf, 0xd9, 0x78,
	0x76, 0x58, 0x19, 0x76, 0x1f, 0x59, 0xa7, 0xbc, 0x4a, 0x0d, 0x9e, 0x42, 0x1c, 0xfa, 0xc1, 0x86,
	0xf6, 0x91, 0x14, 0xb3, 0x38, 0xe3, 0x6f, 0xdd, 0x30, 0xd0, 0x32, 0x8b, 0xd9, 0x01, 0x7f, 0x4b,
	0x88, 0x47, 0xb0, 0x21, 0x73, 0x9e, 0x18, 0x79, 0x21, 0x62, 0x9e, 0xab, 0x3c, 0x18, 0x21, 0x64,
	0xbd, 0x4e, 0x7e, 0x97, 0xab, 0xdc, 0x6e, 0xd6, 0x87, 0xac, 0x93, 0x8a, 0x07, 0xf0, 0x55, 0xb0,
	0x1e, 0x1b, 0x8b, 0x2a, 0x58, 0x91, 0x56, 0x05, 0x21, 0x9b, 0xbe, 0x0a, 0x02, 0x76, 0x61, 0x54,
	0xe5, 0xe2, 0x42, 0x26, 0x86, 0x9f, 0xa4, 0x22, 0xb8, 0x45, 0x16, 0xf3, 0x52, 0xec, 0x1b, 0xb8,
	0x7f, 0x26, 0x85, 0xe6, 0x3a, 0x39, 0x93, 0x09, 0x4f, 0x63, 0x77, 0x0f, 0xd1, 0x09, 0xdd, 0x42,
	0xfc, 0x3d, 0x1f, 0x40, 0x8f, 0xfc, 0x4f, 0x76, 0x98, 0x7d, 0x0d, 0x0b, 0x43, 0x71, 0x79, 0xc9,
	0x0b, 0xc7, 0xdc, 0x46, 0xe6, 0x1d, 0x7f, 0x78, 0x72, 0xc9, 0x0b, 0xe2, 0x3d, 0x84, 0x11, 0x9e,
	0xa3, 0x98, 0x1c, 0xc3, 0x68, 0xd9, 0x98, 0xda, 0x47, 0xdb, 0xec, 0xc0, 0xe0, 0xc8, 0x46, 0xd6,
	0x3b, 0xb7, 0x71, 0xb4, 0x89, 0x59, 0x08, 0xeb, 0xf5, 0x6f, 0x74, 0xd1, 0x27, 0x54, 0x17, 0x3f,
	0xc7, 0xbe, 0x80, 0x6d, 0x9a, 0xc0, 0x37, 0xd4, 0x1d, 0x04, 0xde, 0xc2, 0x81, 0x83, 0xd6, 0x55,
	0xcd, 0x62, 0xc8, 0x5b, 0x77, 0xbd, 0xc5, 0xbc, 0x44, 0x83, 0xfd, 0x1a, 0x88, 0x13, 0xb7, 0x36,
	0xbb, 0x87, 0xa0, 0x4d, 0x4c, 0xff, 0xd4, 0x78, 0xed, 0x11, 0x50, 0x26, 0x6e, 0x1c, 0x17, 0x50,
	0xbd, 0x31, 0x3b, 0x26, 0xdb, 0x3d, 0xa9, 0xd5, 0x5a, 0xf3, 0xdd, 0xa7, 0x1d, 0x34, 0x28, 0xeb,
	0xc0, 0xc7, 0x9e, 0x16, 0x19, 0x6d, 0x67, 0x01, 0x45, 0x56, 0x7b, 0x06, 0xac, 0x41, 0xb5, 0x96,
	0xfc, 0xd4, 0xdb, 0xe8, 0xb8, 0xf5, 0xe5, 0x1e, 0xdc, 0x26, 0xf0, 0xa2, 0x3b, 0x1f, 0x20, 0x9a,
	0xea, 0xf5, 0xda, 0xb7, 0x68, 0x53, 0x44, 0x1f, 0xfd, 0x99, 0xa7, 0xfd, 0x5d, 0x8b, 0x7d, 0x5f,
	0x1b, 0x4b, 0xfe, 0xab, 0x0f, 0x68, 0x63, 0xd1, 0xaf, 0x6a, 0x23, 0xfa, 0xe1, 0x7b, 0xda, 0x88,
	0x7d, 0x56, 0x63, 0x7d, 0x27, 0xef, 0xba, 0xcb, 0xcb, 0x0e, 0x1c, 0x7b, 0x76, 0xfe, 0x7d, 0xfd,
	0xea, 0xf8, 0xfc, 0xa6, 0x97, 0x31, 0x19, 0xf9, 0xfb, 0xdc, 0xe8, 0x77, 0xf5, 0xdb, 0xe3, 0x39,
	0xf4, 0xac, 0x85, 0x83, 0x70, 0x19, 0x2e, 0x52, 0xd8, 0xb7, 0xcd, 0x1b, 0xe1, 0xd1, 0x32, 0xe4,
	0xfa, 0xc5, 0xb1, 0x0f, 0xc3, 0x1f, 0xf1, 0xd7, 0xd1, 0xfe, 0x38, 0x78, 0xbc, 0x8c, 0x42, 0xcb,
	0x0b, 0x05, 0x8c, 0xbc, 0x91, 0xf6, 0x3d, 0xdb, 0xf1, 0xde, 0xb3, 0x6d, 0x07, 0xb0, 0xf2, 0x81,
	0x0e, 0xa0, 0xfb, 0xc1, 0x0e, 0xa0, 0xb7, 0xd0, 0x01, 0x84, 0x06, 0xb6, 0xae, 0x36, 0x1e, 0xec,
	0x29, 0x6c, 0xd9, 0xce, 0xe5, 0x5c, 0xa6, 0xf6, 0x1c, 0x95, 0xf8, 0x88, 0x68, 0xda, 0x4d, 0xa5,
	0xb2, 0x1f, 0x65, 0x9a, 0xbe, 0xa4, 0x2c, 0xfb, 0x14, 0x86, 0x55, 0x3e, 0x15, 0xda, 0x76, 0x3a,
	0x6e, 0x0d, 0x03, 0x4c, 0x1c, 0xaa, 0xcc, 0xde, 0xbb, 0xb5, 0x4c, 0xfd, 0x76, 0x70, 0xf4, 0xf0,
	0xbf, 0xab, 0x30, 0x6c, 0x5a, 0x3f, 0xc6, 0x61, 0x47, 0xaa, 0xb8, 0x14, 0xfa, 0x42, 0x26, 0x22,
	0x3e, 0x79, 0x67, 0x44, 0x19, 0x6b, 0x91, 0x54, 0xba, 0x94, 0x17, 0xc2, 0x75, 0xcb, 0x8f, 0x6f,
	0xe8, 0x21, 0xa9, 0x7e, 0xf7, 0xa4, 0x9a, 0x90, 0xcc, 0x0b, 0xab, 0x12, 0xd5, 0x22, 0xec, 0x67,
	0xb8, 0xd3, 0x4e, 0x31, 0xf5, 0xd4, 0x57, 0x96, 0x50, 0xbf, 0xdd, 0xa8, 0x4f, 0x5b, 0xe5, 0x23,
	0xb8, 0x2d, 0x55, 0xfc, 0x4b, 0x25, 0xaa, 0x05, 0xdd, 0xee, 0x12, 0xba, 0xdb, 0x52, 0xbd, 0x41,
	0x7e, 0xab, 0x1a, 0xc3, 0x7d, 0xaf, 0x24, 0xf6, 0xbd, 0xed, 0x69, 0xf7, 0x96, 0xd0, 0xbe, 0xdb,
	0xac, 0xd9, 0xbe, 0xe7, 0xdb, 0x09, 0xfe, 0x02, 0x77, 0xa5, 0x8a, 0x2f, 0xb9, 0x34, 0x57, 0xd5,
	0x57, 0x97, 0xab, 0xc8, 0x4f, 0x5c, 0x9a, 0x45, 0x69, 0xaa, 0x48, 0x26, 0xf4, 0x6c, 0xa1, 0x22,
	0x6b, 0xcb, 0x55, 0xe4, 0x00, 0xf9, 0xad, 0xea, 0x18, 0xb6, 0xa5, 0xba, 0xba, 0xd6, 0xfe, 0x12,
	0x9a, 0xb7, 0xa4, 0x5a, 0x5c, 0xe7, 0x1b, 0xd8, 0x2e, 0x45, 0x62, 0x94, 0xf6, 0xdd, 0x36, 0x58,
	0x42, 0x71, 0xcb, 0xd1, 0x1b, 0xc9, 0xf0, 0x02, 0xa0, 0x1d, 0x67, 0x9b, 0xb0, 0xa2, 0x0a, 0x3c,
	0x39, 0xc3, 0x68, 0x45, 0x15, 0xb6, 0x79, 0x9c, 0xda, 0xcb, 0x8d, 0x8e, 0xeb, 0x30, 0x72, 0x91,
	0x3d, 0xc5, 0x19, 0x7f, 0xab, 0xea, 0x4e, 0x93, 0x02, 0xcc, 0xca, 0x5c, 0x69, 0x77, 0x62, 0x29,
	0xb0, 0xd9, 0x0b, 0x9e, 0x56, 0xa2, 0x6e, 0x9b, 0x30, 0x08, 0xff, 0xd6, 0x81, 0x41, 0xfd, 0x41,
	0xc4, 0xbe, 0xf5, 0x9b, 0xf5, 0xee, 0xc7, 0xbf, 0xbf, 0x2c, 0x89, 0x36, 0xd3, 0x74, 0xf4, 0xcf,
	0xdb, 0x8e, 0xfe, 0xff, 0x26, 0xbb, 0xb6, 0x5f, 0xc0, 0xb0, 0xc9, 0x79, 0xbb, 0xed, 0x2c, 0xec,
	0xf6, 0x21, 0x8c, 0xce, 0x12, 0x1e, 0x9f, 0xf1, 0x7c, 0x9a, 0x0a, 0x6a, 0x5c, 0x37, 0x22, 0x38,
	0x4b, 0xf8, 0x2b, 0xca, 0xd4, 0x00, 0x75, 0xf2, 0x56, 0x24, 0xa6, 0xc4, 0xa2, 0x10, 0xe0, 0x90,
	0x32, 0xe1, 0x3f, 0x56, 0x60, 0xe4, 0x7d, 0xc3, 0xd9, 0x46, 0x3d, 0xe7, 0x59, 0x3d, 0x0f, 0xfe,
	0xb6, 0x97, 0x8f, 0x9e, 0xd3, 0x5d, 0xe2, 0x2e, 0xa6, 0xbe, 0x9e, 0xe3, 0xa5, 0xc0, 0x3e, 0x03,
	0xd0, 0xf3, 0xb8, 0xe0, 0xc9, 0xb9, 0x70, 0xf2, 0xbd, 0x68, 0xa8, 0xe7, 0x63, 0x4a, 0xd8, 0x3b,
	0x4d, 0xcf, 0x63, 0xa1, 0xb5, 0xd2, 0xa5, 0xab, 0xfd, 0x40, 0xcf, 0xbf, 0xc7, 0xd8, 0x71, 0xa7,
	0x5a, 0xd9, 0x8e, 0xc3, 0x3d, 0x83, 0xa1, 0x9e, 0xbf, 0xa4, 0x84, 0x9d, 0xd5, 0xd4, 0xb3, 0x52,
	0xf7, 0xda, 0x37, 0xed, 0xac, 0xa6, 0x9d, 0x95, 0xba, 0xd7, 0xa1, 0xf1, 0x67, 0x35, 0xcd, 0xac,
	0xd4, 0xc0, 0x0e, 0x8c, 0x37, 0xab, 0x69, 0x67, 0x1d, 0xd6, 0x5c, 0x37, 0x6b, 0xf8, 0xef, 0x0e,
	0x8c, 0xbc, 0xaf, 0x51, 0x5b, 0xc0, 0x5c, 0xc7, 0x65, 0x2a, 0x44, 0x61, 0x3f, 0x9c, 0xe8, 0xea,
	0x86, 0x5c, 0x4f, 0x5c, 0xc6, 0xea, 0xe5, 0x3a, 0xd6, 0x55, 0x9e, 0xd7, 0x1f, 0x56, 0xbd, 0x68,
	0x98, 0xeb, 0x88, 0x12, 0x6e, 0xb8, 0x34, 0x34, 0x5d, 0xb7, 0x1e, 0x9e, 0x50, 0x82, 0xfd, 0x06,
	0x58, 0xae, 0xe3, 0x2a, 0x97, 0xb9, 0x11, 0x5a, 0x57, 0x85, 0x91, 0x27, 0x4d, 0x87, 0xbf, 0x9d,
	0xeb, 0xe3, 0xc5, 0x01, 0xf6, 0x00, 0xd5, 0xdc, 0x65, 0xe3, 0x4a, 0x36, 0xc8, 0xf5, 0x6b, 0xbc,
	0x39, 0x4e, 0xd6, 0xf0, 0x3f, 0x94, 0xaf, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xc7, 0xd3,
	0x97, 0x53, 0x11, 0x00, 0x00,
}
